### ISSUE TITLE
Icons are broken

### ISSUE THREAD

**Issue by rzfzr** [KevinVandy/multi-monitor_calculator#16]
![image](https://user-images.githubusercontent.com/13456224/206790138-ab3d1667-cc16-493b-a442-aec0cc1a6df4.png)

**Comment by KevinVandy** [comment]
Maybe a font just failed to download for you? 

<img width="938" alt="image" src="https://user-images.githubusercontent.com/28243511/206828181-22cf5e46-0825-4775-bc5e-0a2b8acb02c4.png">

**Comment by rzfzr** [comment]
Must have been some local issue, sorry about that
