### ISSUE TITLE
12:5 aspect ratio and/or custom aspect ratio

### ISSUE THREAD

**Issue by skrln** [KevinVandy/multi-monitor_calculator#24]
Feature request to add 12:5 aspect ratio to the dropdownlist, (and optionally) possibility to supply custom aspect ratio.

**Comment by KevinVandy** [comment]
I'll reject suggestions for even more aspect ratios, because custom aspect ratios and resolutions are already supported. Literally just type in the resolution you want.

In fact, I'm probably going to simplify and remove rare aspect ratios from the drop-down soon.
