### ISSUE TITLE
Add 1920x1200 (UXGA), probably remove FHD+

### ISSUE THREAD

**Issue by CJPczk** [KevinVandy/multi-monitor_calculator#26]
I think 1920x1200 (UXGA) should be added to the drop-down.  If there's concerns about cluttering the menu, I think "FHD+" should be removed.

There's currently about thirty 1920x1200 monitors on NewEgg, and zero "FHD+", and I don't recall ever seeing a "FHD+" computer monitor; it seems to be a smartphone thing.  1920x1200 is an extremely popular resolution for business/professional monitors.

On the wikipedia article "List_of_computer_display_standards" there is no mention of "FHD+".  A google search shows that "FHD+" is 2220x1080 or 2160 x 1440, whereas this program shows 2130x1200.  It seems "FHD+" does not have an agreed upon standard.

**Comment by KevinVandy** [comment]
already exists, it's just called FHD+

![image](https://github.com/user-attachments/assets/9aca1283-53e2-4f20-bc76-59f6483f7821)
